site_name: Temari de Grec – 1r Batxillerat
site_description: Apunts i temari adaptats a partir de Mª Felicidad Mafé Durà
site_author: Mª Felicidad Mafé Durà, Olga García Sayalero, Laura Lamata Meana (autores), JB Talens (editor)
site_url: https://juatafe.github.io/Grec1/
use_directory_urls: false
docs_dir: 'md-docs'
site_dir: 'docs'

theme:
  name: material
  language: ca
  favicon: assets/img/favicon.ico
  logo: assets/img/llopislogo.svg
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
    - scheme: slate
      primary: indigo
      accent: light blue
  features:
    - navigation.footer  # ⬅️ Aquesta és la clau!

extra:
  logo: |
    <div class="md-logo-container">
      <a href="https://portal.edu.gva.es/iesllopis" target="_blank" class="logo-llopis"></a>
      <a href="https://ceice.gva.es/va/web/educacion" target="_blank" class="logo-gvanext"></a>
    </div>


  authors:
    - nom: Olga García Sayalero
      rol: Autora dels materials originals
    - nom: Laura Lamata Meana
      rol: Autora dels materials originals
    - nom: Mª Felicidad Mafé Durà
      rol: Adaptadora de l’obra
    - nom: JB Talens
      rol: Editor i adaptador web
  generator: false
  consent:
    title: Consentiment de cookies
    description: Utilitzem cookies per millorar l'experiència de navegació.

copyright: |
  <div class="custom-footer">
    <div class="footer-logo footer-left"></div>
    <span class="footer-text">
      © 2025 García Sayalero, Lamata Meana — Adaptació Mafé Durà — Publicació JB Talens.<br>
      Llicència <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ca" target="_blank">CC BY-NC-SA 4.0</a>
    </span>
    <div class="footer-logo footer-right"></div>
  </div>


extra_css:
  - assets/stylesheets/extracsspdf.css
  - assets/stylesheets/customs.css
  - assets/stylesheets/extra.css

nav:
  - Inici: index.md
  - "Tema 1: L’alfabet grec":
      - Introducció: tema1/index.md
      - De l’alfabet fenici al grec: tema1/del-fenici-al-grec.md
      - Taula comparativa i tipus d’escriptura: tema1/taula-comparativa.md
      - Del grec al llatí i altres alfabets: tema1/alfabet-llati-i-altres.md
      - Un poc de mitologia: tema1/mitologia-europa.md
      - Lletres i sons: tema1/taula-lletres.md
      - Pronunciació: tema1/pronunciacio.md
      - Com s’escriu?: tema1/com-sescriu.md
      - Activitats: tema1/activitats.md
      - Fonemes i esperits: tema1/fonemes-i-esperits.md
      - Accents i paraules àtones: tema1/accents.md
      - Paraules àtones: tema1/atones.md
      - Signes ortogràfics: tema1/signes-ortografics.md
      - Activitats de signes i accents: tema1/activitats-accents.md
      - Autoavaluació: tema1/autoavaluacio.md
  - "Tema 2: Morfologia i sintaxi gregues":
      - Llengua flexiva: tema2/1-llengua-flexiva.md
      - Funcions i casos: tema2/2-Funcions-Prin-Casos.md
      - Activitats: tema2/3-Activitats.md
  - "Tema 3: L’article i 2a declinació":
      - L’article: tema3/1-article.md
      - Segona declinació: tema3/2-naDecli.md
      - Guia per a traduir: tema3/3-guia-traduccio.md
      - Etimologia: tema3/4-etimologia.md
      - Prefixos, sufixos i lexemes: tema3/5-prefixos-suf-lex.md
      - Activitats: tema3/6-Activitats.md
  - "Tema 4: Flexió verbal i present d’indicatiu":
      - Introducció i tipus de verb: tema4/1-flexio-verbal.md
      - Desinències i temes verbals: tema4/2-desinencies-temes.md
      - Verb λύω i εἰμί: tema4/3-verb-luo-eimi.md
      - Activitats i autoavaluació: tema4/4-activitats.md




markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  # Extensió per Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format